"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Wand2, ArrowRight, Lightbulb, Target } from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

/**
 * RecommendedActionsCard — the OS's suggested next moves. Composes real data
 * (no fabrication):
 *   - recommendedTopics() → "Learn X" action rows (deterministic, grounded in
 *     goal + industry + mock weaknesses)
 *   - CoachInsight rows with kind:"recommendation" (AI-generated by nudgeNow /
 *     the weekly cron)
 * Each row links to the surface where the user can act.
 *
 * @param {{ recommendations: any[], coachInsights: any[] }} props
 */
export default function RecommendedActionsCard({
  recommendations = [],
  coachInsights = [],
}) {
  const recInsights = (coachInsights ?? []).filter((i) => i.kind === "recommendation");
  const recs = (recommendations ?? []).slice(0, 4);

  const rows = [
    ...recs.map((r) => ({
      icon: Target,
      accent: "text-primary",
      title: `Learn ${r.skill}`,
      why: r.why || "A recommended next skill for your goal.",
      href: "/learning",
      cta: "Open learning",
    })),
    ...recInsights.slice(0, 3).map((i) => ({
      icon: Lightbulb,
      accent: "text-accent",
      title: i.title,
      why: i.body || "A suggested next move from your AI copilot.",
      href: i.href || "/coach",
      cta: "Act on it",
    })),
  ];

  return (
    <Card className="glass overflow-hidden">
      <CardHeader className="flex flex-row items-center justify-between space-y-0">
        <div>
          <CardTitle className="flex items-center gap-2 text-base">
            <span className="grid h-7 w-7 place-items-center rounded-lg bg-primary/15 text-primary">
              <Wand2 className="h-4 w-4" />
            </span>
            Recommended actions
          </CardTitle>
          <CardDescription className="mt-1">
            The OS&rsquo;s suggested next moves, grounded in your activity and memory.
          </CardDescription>
        </div>
        <Link
          href="/coach"
          className="flex items-center gap-1 text-xs font-medium text-primary transition-colors hover:text-accent"
        >
          Ask copilot <ArrowRight className="h-3 w-3" />
        </Link>
      </CardHeader>
      <CardContent>
        {rows.length === 0 ? (
          <div className="flex flex-col items-center gap-2 py-6 text-center">
            <Wand2 className="h-8 w-8 text-muted-foreground/60" />
            <p className="max-w-xs text-sm text-muted-foreground">
              Run a few activities and the OS will recommend your next moves here.
            </p>
            <Link
              href="/learning"
              className="mt-1 inline-flex items-center gap-1 text-xs font-medium text-primary transition-colors hover:text-accent"
            >
              Browse learning <ArrowRight className="h-3 w-3" />
            </Link>
          </div>
        ) : (
          <ul className="space-y-2">
            {rows.slice(0, 5).map((row, i) => {
              const Icon = row.icon;
              return (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, y: 6 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.04 }}
                >
                  <Link
                    href={row.href}
                    className="flex items-start gap-3 rounded-xl border border-border bg-background/40 p-3 transition-colors hover:border-primary/30 hover:bg-accent/5"
                  >
                    <Icon className={`mt-0.5 h-4 w-4 shrink-0 ${row.accent}`} />
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium text-foreground">{row.title}</p>
                      <p className="line-clamp-2 text-xs text-muted-foreground">{row.why}</p>
                    </div>
                    <ArrowRight className="mt-1 h-3.5 w-3.5 shrink-0 text-muted-foreground" />
                  </Link>
                </motion.li>
              );
            })}
          </ul>
        )}
      </CardContent>
    </Card>
  );
}